/**
 * Embed the built UMD bundle as a C string literal.
 *
 * Usage:
 *   node scripts/embed-to-c.js
 *
 * Reads  web/dist/wm8741-ble.umd.js
 * Writes main/wm8741_ble_js.h
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const projectRoot = resolve(__dirname, '..', '..');
const inputPath = resolve(projectRoot, 'web', 'dist', 'wm8741-ble.umd.js');
const outputPath = resolve(projectRoot, 'main', 'wm8741_ble_js.h');

const jsContent = readFileSync(inputPath, 'utf-8');

// Escape the JS string for embedding in a C string literal.
function escapeForCString(input) {
  return input
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n"\n"')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

const escaped = escapeForCString(jsContent);

const header = `/*
 * Auto-generated by web/scripts/embed-to-c.js
 * Do not edit manually.
 */

#ifndef WM8741_BLE_JS_H
#define WM8741_BLE_JS_H

static const char wm8741_ble_js[] =
"${escaped}";

#endif /* WM8741_BLE_JS_H */
`;

writeFileSync(outputPath, header, 'utf-8');
console.log(`Embedded ${inputPath} -> ${outputPath}`);
console.log(`Original size: ${jsContent.length} bytes`);
